# Build image: restore and publish
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Restore with project files only (better layer caching)
COPY src/WebAutomatorCore/WebAutomatorCore.csproj src/WebAutomatorCore/
COPY src/WebAutomatorLambda/WebAutomatorLambda.csproj src/WebAutomatorLambda/
RUN dotnet restore src/WebAutomatorLambda/WebAutomatorLambda.csproj

# Copy the rest of the source
COPY . .

# Build and publish Lambda project
RUN dotnet build src/WebAutomatorLambda/WebAutomatorLambda.csproj -c Release --no-restore
RUN dotnet publish src/WebAutomatorLambda/WebAutomatorLambda.csproj -c Release -o /app/publish --no-restore

# Download Chromium (and deps) into the published artifacts using Playwright script generated by the build
ENV PLAYWRIGHT_BROWSERS_PATH=/app/publish/ms-playwright
WORKDIR /src/src/WebAutomatorLambda
RUN pwsh -File bin/Release/net8.0/playwright.ps1 install --with-deps chromium
WORKDIR /src

# Runtime image: AWS Lambda .NET 8
FROM public.ecr.aws/lambda/dotnet:8
WORKDIR /var/task

# Copy published application
COPY --from=build /app/publish ./
# Ensure .runtimeconfig.json is included in the publish directory
COPY --from=build /app/publish/WebAutomatorLambda.runtimeconfig.json ./

CMD ["WebAutomatorLambda::WebAutomatorLambda.Handler::LambdaHandler"]
